// evmone: Fast Ethereum Virtual Machine implementation
// Copyright 2026 The evmone Authors.
// SPDX-License-Identifier: Apache-2.0
#pragma once

#include <filesystem>
#include <span>
#include <string>
#include <vector>

namespace evmone::test
{
/// A test file found under a search root.
struct TestFile
{
    std::filesystem::path path;

    /// The file's directory relative to the root, which is the test suite it belongs to.
    std::string suite_name;

    /// Ordered by path, because that is the order a run visits them in. The suite name is derived
    /// from the path, so it never gets to decide a comparison.
    auto operator<=>(const TestFile&) const = default;
};

/// The JSON test files under @p root, sorted, so a run visits them in a stable order.
/// "index.json" is skipped: those are lists of tests generated by other tools, not tests.
[[nodiscard]] std::vector<TestFile> collect_test_files(const std::filesystem::path& root);

/// Drops from @p files everything under one of the @p ignored paths, which are relative to the
/// search root. Whole path components are matched, so ignoring "bc4895" keeps
/// "bc4895-withdrawals".
void ignore_test_files(
    std::vector<TestFile>& files, std::span<const std::filesystem::path> ignored);
}  // namespace evmone::test
